# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portview < Formula
  desc "Lightweight web-based port monitor"
  homepage "https://github.com/vcdim/portview"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/portview/releases/download/v0.2.0/portview_0.2.0_darwin_amd64.tar.gz"
      sha256 "bc32240f0c7bce0e77612d37a12dd3d985f87d08b5341888ba16e08db30c6a76"

      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/portview/releases/download/v0.2.0/portview_0.2.0_darwin_arm64.tar.gz"
      sha256 "1ce10f24c74b90421c2de5baf5ca881cb49ac717e937297ffea64b27d353b6e5"

      define_method(:install) do
        bin.install "portview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.2.0/portview_0.2.0_linux_amd64.tar.gz"
      sha256 "9339023dc4daa9e81529c9edd0031e7278c7058106e277f6f0367ec2a5aaba6f"
      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.2.0/portview_0.2.0_linux_arm64.tar.gz"
      sha256 "a2c685aa0aa8e474347cea59fb8b0c169af9eff2b1d8c17885b5c41ed9a7484b"
      define_method(:install) do
        bin.install "portview"
      end
    end
  end
end
