# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portview < Formula
  desc "Lightweight web-based port monitor"
  homepage "https://github.com/vcdim/portview"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/portview/releases/download/v0.3.3/portview_0.3.3_darwin_amd64.tar.gz"
      sha256 "9f47b53bc4c676627a654a02c105d3bedbcdf04efc44bf9760ab7e426fc194a0"

      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/portview/releases/download/v0.3.3/portview_0.3.3_darwin_arm64.tar.gz"
      sha256 "c55379adae1f443578e0e061fdc2dafd16d2b8fa9e34263468ef1fa5d2cf0ff2"

      define_method(:install) do
        bin.install "portview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.3.3/portview_0.3.3_linux_amd64.tar.gz"
      sha256 "ec6d90cba0fb6bf5e82e102a771089760e007dc896a2eb5941122f282f588d15"
      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.3.3/portview_0.3.3_linux_arm64.tar.gz"
      sha256 "09ce0bd7b48155ccaef17d6ba8af4be9ca80a4c3f3b01c2b5a5326a702505c5b"
      define_method(:install) do
        bin.install "portview"
      end
    end
  end
end
