# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portview < Formula
  desc "Lightweight web-based port monitor"
  homepage "https://github.com/vcdim/portview"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/portview/releases/download/v0.2.4/portview_0.2.4_darwin_amd64.tar.gz"
      sha256 "8a9d6da1807243217e9679f35fbbccf0dcbaceaddb0d945bfb6e540723cbe990"

      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/portview/releases/download/v0.2.4/portview_0.2.4_darwin_arm64.tar.gz"
      sha256 "8bec128397afc9719332b8774702169c40de146228131f5b84a24b73d0af6068"

      define_method(:install) do
        bin.install "portview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.2.4/portview_0.2.4_linux_amd64.tar.gz"
      sha256 "cca7e529400dd148f9e43dea51cce873e62892a2292ef650b3bb5af96d683f91"
      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.2.4/portview_0.2.4_linux_arm64.tar.gz"
      sha256 "d2ca519ec84656fbd59ffbe7e4b3b4752cb6db160b45967299b07cabcd23a963"
      define_method(:install) do
        bin.install "portview"
      end
    end
  end
end
