# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webtop < Formula
  desc "Lightweight web-based system dashboard"
  homepage "https://github.com/vcdim/webtop"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.3/webtop_0.4.3_darwin_amd64.tar.gz"
      sha256 "21adc559a0743ec69f9e61c42f39c598a7e32942e904fc5ebbae8a4919603582"

      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.3/webtop_0.4.3_darwin_arm64.tar.gz"
      sha256 "c585ed155efe4f0034f5d7ce1915ea604a2e64728f2f892e1f094e09d6d27263"

      define_method(:install) do
        bin.install "webtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.3/webtop_0.4.3_linux_amd64.tar.gz"
      sha256 "f143f9c01e029bfd944b92934e424e309ae5481793c69d189d1240a573c860ae"
      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.3/webtop_0.4.3_linux_arm64.tar.gz"
      sha256 "1709f91d404c55bcd78963879426862f6b63cfbdf8340492081347fb84d18476"
      define_method(:install) do
        bin.install "webtop"
      end
    end
  end
end
